# Generated by Django 4.2.5 on 2023-09-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_timeslot_coach_notes_timeslot_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='coach_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
