# Generated by Django 4.2.5 on 2023-09-20 03:32

import datetime
from django.db import migrations, models
import scheduler.validators


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_timeslot_coach_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, validators=[scheduler.validators.validate_start_time]),
        ),
    ]
