# Generated by Django 4.2.5 on 2023-09-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_remove_timeslot_time_timeslot_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
